
public class Aman {

	public static void main(String arg[]) {
		// TODO Auto-generated method stub
            byte amassdddhfjjehfdvmdsdhsfhsdbvcdsbcshdbhdbshchdvbsdhvdshvdshvccdshcsdhcsdhvchvcdhsvdshvdcvsdhvdshhdsvhdvchsvdchdsvshvddschdsvhcvshcvsdhchdvdchvdshvhdsvchdsvchsdvhcvsdhvcdshvhcdshcvhdsvcdssdhsdcvhdsdsvhcvdshvhchdvchsdvchdvshvcsdhvchdvhcdvchdamassdddhfjjehfdvmdsdhsfhsdbvcdsbcshdbhdbshchdvbsdhvdshvdshvccdshcsdhcsdhvchvcdhsvdshvdcvsdhvdshhdsvhdvchsvdchdsvshvddschdsvhcvshcvsdhchdvdchvdshvhdsvchdsvchsdvhcvsdhvcdshvhcdshcvhdsvcdssdhsdcvhdsdsvhcvdshvhchdvchsdvchdvshvcsdhvchdvhcdvchd = 2;
            System.out.println(amassdddhfjjehfdvmdsdhsfhsdbvcdsbcshdbhdbshchdvbsdhvdshvdshvccdshcsdhcsdhvchvcdhsvdshvdcvsdhvdshhdsvhdvchsvdchdsvshvddschdsvhcvshcvsdhchdvdchvdshvhdsvchdsvchsdvhcvsdhvcdshvhcdshcvhdsvcdssdhsdcvhdsdsvhcvdshvhchdvchsdvchdvshvcsdhvchdvhcdvchdamassdddhfjjehfdvmdsdhsfhsdbvcdsbcshdbhdbshchdvbsdhvdshvdshvccdshcsdhcsdhvchvcdhsvdshvdcvsdhvdshhdsvhdvchsvdchdsvshvddschdsvhcvshcvsdhchdvdchvdshvhdsvchdsvchsdvhcvsdhvcdshvhcdshcvhdsvcdssdhsdcvhdsdsvhcvdshvhchdvchsdvchdvshvcsdhvchdvhcdvchd);
	}

}
